# Generated by Django 4.2 on 2023-09-27 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Immagine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Descrizione', models.CharField(max_length=500)),
                ('immagine', models.ImageField(upload_to='immagini_da_modificare/')),
                ('data_caricamento', models.DateTimeField(auto_now_add=True)),
                ('stato', models.CharField(default='da modificare', max_length=100)),
                ('foto_modificata', models.ImageField(blank=True, null=True, upload_to='foto_modificate/')),
            ],
        ),
        migrations.CreateModel(
            name='Servizio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('reflex', models.BooleanField()),
                ('actioncam', models.BooleanField()),
                ('drone', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'Servizi',
            },
        ),
    ]
