# Generated by Django 4.2 on 2023-10-02 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Immagine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Descrizione', models.CharField(max_length=500)),
                ('immagine', models.ImageField(upload_to='immagini_da_modificare/')),
                ('data_caricamento', models.DateTimeField(auto_now_add=True)),
                ('stato', models.CharField(default='da modificare', max_length=100)),
                ('foto_modificata', models.ImageField(blank=True, null=True, upload_to='foto_modificate/')),
            ],
        ),
        migrations.CreateModel(
            name='Servizio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('reflex', models.BooleanField()),
                ('actioncam', models.BooleanField()),
                ('drone', models.BooleanField()),
                ('cliente', models.ForeignKey(default='Blyad ', on_delete=django.db.models.deletion.CASCADE, related_name='servizio_cliente', to=settings.AUTH_USER_MODEL)),
                ('fotografi', models.ManyToManyField(default='Blyad ', related_name='servizio_fotografi', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Servizi',
            },
        ),
    ]
