# Generated by Django 4.2 on 2023-10-06 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Gestione', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servizio',
            name='cliente',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='servizio_cliente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='servizio',
            name='fotografi',
            field=models.ManyToManyField(default='0', related_name='servizio_fotografi', to=settings.AUTH_USER_MODEL),
        ),
    ]
