# Generated by Django 4.2 on 2023-10-09 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Gestione', '0002_alter_servizio_cliente_alter_servizio_fotografi'),
    ]

    operations = [
        migrations.AddField(
            model_name='immagine',
            name='cliente',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='immagine_cliente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='immagine',
            name='fotografi',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='immagine_fotografi', to=settings.AUTH_USER_MODEL),
        ),
    ]
